# Generated by Django 2.2.1 on 2019-11-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datatype', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatype',
            name='generic',
            field=models.BooleanField(choices=[(0, 'Custom'), (1, 'Generic')], db_index=True),
        ),
    ]
