# Generated by Django 2.2.1 on 2019-11-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='generic',
            field=models.BooleanField(db_index=True, default=True),
            preserve_default=False,
        ),
    ]
