# Generated by Django 2.2.1 on 2019-11-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_auto_20191111_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='generic',
            field=models.BooleanField(choices=[(0, 'Custom'), (1, 'Generic')], db_index=True),
        ),
    ]
