# Generated by Django 2.2.1 on 2019-11-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_auto_20191111_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'Text'), (1, 'Number'), (2, 'Datetime'), (3, 'Enumeration'), (4, 'Video'), (5, 'Audio'), (6, 'Image'), (7, 'Email'), (8, 'URL')]),
        ),
    ]
