# Generated by Django 2.2.1 on 2019-11-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_auto_20191111_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='required',
            field=models.BooleanField(db_index=True, default=False),
            preserve_default=False,
        ),
    ]
