# Generated by Django 2.2.1 on 2019-11-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_property_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'Text'), (1, 'Number'), (2, 'Datetime'), (4, 'Video'), (5, 'Audio'), (6, 'Image'), (7, 'Email'), (8, 'URL')]),
        ),
    ]
