# Generated by Django 2.2.1 on 2019-11-25 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_auto_20191114_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='datatype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datatype.DataType'),
        ),
    ]
