# Generated by Django 2.2.1 on 2020-01-02 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_auto_20191125_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'Text'), (1, 'Number'), (2, 'Datetime'), (4, 'Video'), (5, 'Audio'), (6, 'Image'), (7, 'Email'), (8, 'URL'), (9, 'Location')]),
        ),
    ]
