# Generated by Django 2.2.1 on 2019-11-13 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integerfield', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integerfield',
            name='value',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
