# Generated by Django 2.2.1 on 2019-11-14 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instance', '0001_initial'),
        ('property', '0006_property_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateTimeField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='instance.Instance')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='property.Property')),
            ],
            options={
                'verbose_name': 'datetimefield',
                'verbose_name_plural': 'datetimefields',
            },
        ),
    ]
