# Generated by Django 2.2.1 on 2019-11-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datetimefield', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datetimefield',
            name='value',
            field=models.DateField(blank=True, null=True),
        ),
    ]
