# Generated by Django 2.2.1 on 2019-12-09 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datetimefield', '0003_auto_20191125_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datetimefield',
            name='value',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
