# Generated by Django 2.2.1 on 2019-11-11 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property', '0001_initial'),
        ('instance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='instance.Instance')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='property.Property')),
            ],
            options={
                'verbose_name': 'textfield',
                'verbose_name_plural': 'textfields',
            },
        ),
    ]
