# Generated by Django 2.2.1 on 2019-11-13 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textfield', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textfield',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
