# Generated by Django 2.2.1 on 2019-11-06 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_auto_20191106_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='community.Community'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
