# Generated by Django 2.2.1 on 2019-11-05 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_subscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
