# Generated by Django 2.2.1 on 2019-11-07 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0009_remove_community_datatype'),
    ]

    operations = [
        migrations.AddField(
            model_name='datatype',
            name='type',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('type', models.SmallIntegerField()),
                ('datatype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='community.DataType')),
            ],
            options={
                'verbose_name': 'property',
                'verbose_name_plural': 'properties',
            },
        ),
    ]
