# Generated by Django 2.2.1 on 2019-11-07 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0011_auto_20191107_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatype',
            name='type',
            field=models.BooleanField(db_index=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.SmallIntegerField(db_index=True),
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(default=7, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('datatype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='community.DataType')),
            ],
            options={
                'verbose_name': 'datatype',
                'verbose_name_plural': 'datatypes',
            },
        ),
    ]
