# Generated by Django 2.2.1 on 2019-11-07 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0012_auto_20191107_1533'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instance',
            options={'verbose_name': 'instance', 'verbose_name_plural': 'instances'},
        ),
        migrations.RenameField(
            model_name='datatype',
            old_name='type',
            new_name='generic',
        ),
    ]
