# Generated by Django 2.2.1 on 2019-11-07 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0014_integerfield_textfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='integerfield',
            name='property',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='community.Property'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='textfield',
            name='property',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='community.Property'),
            preserve_default=False,
        ),
    ]
