# Generated by Django 2.2.1 on 2019-11-08 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0015_auto_20191107_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='datatype',
            name='community',
            field=models.ForeignKey(default=25, on_delete=django.db.models.deletion.PROTECT, to='community.Community'),
            preserve_default=False,
        ),
    ]
