# Generated by Django 2.2.1 on 2019-11-08 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0016_datatype_community'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instance',
            name='author',
        ),
        migrations.RemoveField(
            model_name='instance',
            name='datatype',
        ),
        migrations.RemoveField(
            model_name='integerfield',
            name='instance',
        ),
        migrations.RemoveField(
            model_name='integerfield',
            name='property',
        ),
        migrations.RemoveField(
            model_name='property',
            name='datatype',
        ),
        migrations.RemoveField(
            model_name='textfield',
            name='instance',
        ),
        migrations.RemoveField(
            model_name='textfield',
            name='property',
        ),
        migrations.DeleteModel(
            name='DataType',
        ),
        migrations.DeleteModel(
            name='Instance',
        ),
        migrations.DeleteModel(
            name='IntegerField',
        ),
        migrations.DeleteModel(
            name='Property',
        ),
        migrations.DeleteModel(
            name='TextField',
        ),
    ]
