# Generated by Django 2.2.1 on 2020-01-02 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0018_remove_community_post_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='author',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
